roboclaw_mapping:
  # my pololu motors (75:1 ratio): https://www.pololu.com/product/4846
  # gobilda motors (26.9:1 ratio): https://www.gobilda.com/5202-series-yellow-jacket-planetary-gear-motor-26-9-1-ratio-223-rpm-3-3-5v-encoder/
  drive_left_front:
    address: 130
    channel: M2
    ticks_per_rev: 48
    gear_ratio: 74.83
  drive_left_middle:
    address: 130
    channel: M1
    ticks_per_rev: 48
    gear_ratio: 74.83
  drive_left_back:
    address: 129
    channel: M2
    ticks_per_rev: 28
    gear_ratio: 26.9
  drive_right_back:
    address: 129
    channel: M1
    ticks_per_rev: 28
    gear_ratio: 26.9
  drive_right_middle:
    address: 128
    channel: M2
    ticks_per_rev: 48
    gear_ratio: 74.83
  drive_right_front:
    address: 128
    channel: M1
    ticks_per_rev: 48
    gear_ratio: 74.83
  # gear ratio for the corner motors is 16/48 as the CPR is measured after the gearbox, but
  # to the output shaft through the gears connecting the absolute encoder
  # ticks per revolution for the absolute analog encoders: 0-2V with 1mV steps --> 2000
  corner_left_front:
    address: 132
    channel: M2
    ticks_per_rev: 2000
    gear_ratio: 0.3333
  corner_left_back:
    address: 132
    channel: M1
    ticks_per_rev: 2000
    gear_ratio: 0.3333
  corner_right_back:
    address: 131
    channel: M2
    ticks_per_rev: 2000
    gear_ratio: 0.3333
  corner_right_front:
    address: 131
    channel: M1
    ticks_per_rev: 2000
    gear_ratio: 0.3333
